# Generated by Django 5.1.6 on 2025-03-05 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0002_verga'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Verga',
        ),
        migrations.AlterField(
            model_name='boleto',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_fin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_inicio',
            field=models.DateTimeField(),
        ),
    ]
