# Generated by Django 5.1.6 on 2025-03-05 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0003_delete_verga_alter_boleto_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='localidad_id',
        ),
        migrations.DeleteModel(
            name='boleto',
        ),
        migrations.DeleteModel(
            name='evento',
        ),
    ]
