# Generated by Django 5.1.6 on 2025-03-05 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0004_remove_evento_localidad_id_delete_boleto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('localidad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examen.localidad')),
            ],
        ),
        migrations.CreateModel(
            name='boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField()),
                ('fecha', models.DateTimeField()),
                ('boletoTipo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examen.boletotipo')),
                ('evento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examen.evento')),
            ],
        ),
    ]
