# Generated by Django 5.1.6 on 2025-03-05 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0005_evento_boleto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleto',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_inicio',
            field=models.DateField(),
        ),
    ]
