# Generated by Django 5.1.6 on 2025-03-05 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0006_alter_boleto_fecha_alter_evento_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleto',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_fin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_inicio',
            field=models.DateTimeField(),
        ),
    ]
